"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load a local .env (KEY=VALUE per line) if present, so secrets like the Gemini
# API key live outside the code (and outside git — see .gitignore). Existing
# environment variables always win over the file.
_ENV_FILE = BASE_DIR / ".env"
if _ENV_FILE.exists():
    for _line in _ENV_FILE.read_text(encoding="utf-8").splitlines():
        _line = _line.strip()
        if not _line or _line.startswith("#") or "=" not in _line:
            continue
        _k, _, _v = _line.partition("=")
        os.environ.setdefault(_k.strip(), _v.strip().strip('"').strip("'"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-z%(%y=4a3t_i$xvzwv*y+6y=&*z*0!d35ty&t=6&a=+5+1g9pz"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "universities",
    "academic_etl",
]

# --- academic_etl settings ---
ETL_VAR_DIR = BASE_DIR / "var"
ETL_HTML_CACHE_DIR = ETL_VAR_DIR / "html_cache"
ETL_USER_AGENT = "BeyondDegreeBot/0.1 (academic data pipeline; contact: linhnguyenthuy0805@gmail.com)"
ETL_REQUEST_TIMEOUT = 15  # seconds
ETL_RATE_LIMIT_SECONDS = 1.5  # min delay between requests to the same domain
ETL_MAX_PAGES_PER_SITE = 12
ETL_MAX_CRAWL_DEPTH = 2
ETL_IMPORT_CONFIDENCE_THRESHOLD = 0.75
ETL_WORKER_STALE_SECONDS = 90
ETL_WORKER_HEARTBEAT_SECONDS = 15

# Scrapling DynamicFetcher fallback for JS-rendered (React/Next/Angular) sites.
# When a static requests fetch returns thin/empty content, re-render the page in
# a headless browser. Off by default (requires Playwright browsers installed via
# `scrapling install`); enable per-run with `crawl_country --dynamic`.
ETL_USE_DYNAMIC_FALLBACK = False
ETL_DYNAMIC_MIN_TEXT_CHARS = 500   # below this much visible text -> page looks JS-thin
ETL_DYNAMIC_TIMEOUT_MS = 30000     # headless browser per-page timeout
ETL_DYNAMIC_NETWORK_IDLE = True    # wait for network idle before snapshotting

# Program detail-page crawling: follow each discovered program/major link and
# extract duration/fees/intake/requirements/etc. with per-field evidence.
ETL_CRAWL_PROGRAM_DETAILS = True
ETL_MAX_PROGRAM_DETAIL_PAGES = 12  # max program detail pages fetched per university

# Prefer the English version of a site when it exposes one (hreflang="en"
# alternate or an English language-switcher link), so a worldwide catalog is
# built in a common language without machine translation.
ETL_PREFER_ENGLISH = True

# Concurrent Wikipedia article fetches during the catalog build (network only;
# parsing and DB writes stay serial).
ETL_WIKIPEDIA_CONCURRENCY = 6

# --- Gemini grounded enrichment ---
# Fills the required fields (name, website, description, campus_student_life,
# number_of_students) from Gemini answers grounded in Google Search, so values
# match what a web search returns instead of fragile per-site HTML scraping.
# The API key is read from the environment / .env — never hardcode it here.
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "") or os.environ.get("GOOGLE_API_KEY", "")
# Optional: several keys (comma-separated) to rotate through — the daily free
# quota is counted per key (project), so rotating multiplies the free budget.
GEMINI_API_KEYS = os.environ.get("GEMINI_API_KEYS", "")
# One model, or a comma-separated fallback chain. Daily quota is also counted
# per model, so listing several lets one key keep going after a model's daily
# cap (e.g. "gemini-2.5-flash,gemini-2.5-flash-lite,gemini-2.0-flash").
GEMINI_MODEL = os.environ.get("GEMINI_MODEL", "gemini-2.5-flash")
GEMINI_CACHE_DIR = ETL_VAR_DIR / "gemini_cache"  # per-institution JSON responses
GEMINI_CONCURRENCY = int(os.environ.get("GEMINI_CONCURRENCY", "4"))  # parallel API calls
GEMINI_MAX_RETRIES = int(os.environ.get("GEMINI_MAX_RETRIES", "4"))  # backoff on 429/5xx
GEMINI_TIMEOUT = int(os.environ.get("GEMINI_TIMEOUT", "60"))  # seconds per request

# --- Exchange rate API ---
ETL_EXCHANGE_RATE_API = os.environ.get("EXCHANGE_RATE_API", "https://api.frankfurter.app/latest")
ETL_EXCHANGE_RATE_CACHE_HOURS = int(os.environ.get("EXCHANGE_RATE_CACHE_HOURS", "24"))

# --- Fanar API (OpenAI-compatible LLM from Qatar) ---
FANAR_API_KEY = os.environ.get("FANAR_API_KEY", "")
FANAR_API_BASE_URL = os.environ.get("FANAR_API_BASE_URL", "https://api.fanar.qa/v1")
FANAR_MODEL = os.environ.get("FANAR_MODEL", "Fanar-C-2-27B")
FANAR_TRANSLATION_MODEL = os.environ.get("FANAR_TRANSLATION_MODEL", "Fanar-Shaheen-MT-1")
FANAR_CACHE_DIR = ETL_VAR_DIR / "fanar_cache"
FANAR_TIMEOUT = int(os.environ.get("FANAR_TIMEOUT", "15"))
FANAR_CONCURRENCY = int(os.environ.get("FANAR_CONCURRENCY", "4"))

# --- LLM provider fallback order ---
ETL_LLM_PROVIDER_ORDER = os.environ.get("ETL_LLM_PROVIDER_ORDER", "fanar,gemini").split(",")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {"format": "{asctime} {levelname} {name} {message}", "style": "{"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "verbose"},
        "etl_file": {
            "class": "logging.FileHandler",
            "filename": str(ETL_VAR_DIR / "etl.log"),
            "formatter": "verbose",
            "encoding": "utf-8",
            "delay": True,
        },
    },
    "loggers": {
        "academic_etl": {
            "handlers": ["console", "etl_file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        "OPTIONS": {"timeout": 30},
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
