# Generated by Django 6.0.6 on 2026-06-11 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("slug", models.SlugField(max_length=500, unique=True)),
                ("location", models.CharField(blank=True, default="", max_length=500)),
                ("country", models.CharField(blank=True, default="", max_length=100)),
                (
                    "country_code",
                    models.CharField(blank=True, default="", max_length=3),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("sponsored", models.BooleanField(default=False)),
                ("website", models.URLField(blank=True, default="", max_length=500)),
                (
                    "global_rank",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "financials",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("student_loan_available", models.BooleanField(default=False)),
                ("campus_student_life", models.TextField(blank=True, default="")),
                (
                    "number_of_students",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "student_to_faculty_ratio",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "international_student_ratio",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("housing_availability", models.BooleanField(default=False)),
                (
                    "admissions_contact",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "admissions_phone",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "admissions_page_link",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("immigration_support", models.BooleanField(default=False)),
                (
                    "university_campuses",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "universities",
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("program_name", models.CharField(max_length=500)),
                (
                    "degree_level",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "field_of_study",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "faculty_or_school",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("duration", models.CharField(blank=True, default="", max_length=100)),
                (
                    "study_mode",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("language", models.CharField(blank=True, default="", max_length=100)),
                (
                    "tuition_fee",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("currency", models.CharField(blank=True, default="", max_length=10)),
                (
                    "program_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="universities.university",
                    ),
                ),
            ],
            options={
                "unique_together": {("university", "program_name", "degree_level")},
            },
        ),
    ]
