# Generated by Django 6.0.6 on 2026-06-11 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2", max_length=2, unique=True
                    ),
                ),
                (
                    "numeric_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ISO 3166-1 numeric",
                        max_length=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "countries",
            },
        ),
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dry_run", models.BooleanField(default=True)),
                ("approved_only", models.BooleanField(default=True)),
                ("confidence_threshold", models.FloatField(default=0.75)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_processed", models.PositiveIntegerField(default=0)),
                ("total_created", models.PositiveIntegerField(default=0)),
                ("total_updated", models.PositiveIntegerField(default=0)),
                ("total_skipped", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PipelineRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_name", models.CharField(max_length=100)),
                (
                    "country_code",
                    models.CharField(blank=True, default="", max_length=2),
                ),
                (
                    "crawl_mode",
                    models.CharField(
                        default="full",
                        help_text="discover_only | full | csv_seed",
                        max_length=20,
                    ),
                ),
                (
                    "seed_provider",
                    models.CharField(
                        default="hipolabs", help_text="hipolabs | csv", max_length=50
                    ),
                ),
                (
                    "crawl_scope",
                    models.CharField(
                        blank=True, default="official_site", max_length=50
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("discovering", "Discovering"),
                            ("crawling", "Crawling"),
                            ("validating", "Validating"),
                            ("review", "Review"),
                            ("importing", "Importing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "total_discovered_institutions",
                    models.PositiveIntegerField(default=0),
                ),
                ("total_crawled_institutions", models.PositiveIntegerField(default=0)),
                ("total_programs_found", models.PositiveIntegerField(default=0)),
                ("stats_json", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FieldEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_type", models.CharField(max_length=30)),
                ("entity_id", models.PositiveIntegerField()),
                ("field_name", models.CharField(max_length=100)),
                ("extracted_value", models.TextField(blank=True, default="")),
                ("normalized_value", models.TextField(blank=True, default="")),
                (
                    "source_url",
                    models.URLField(blank=True, default="", max_length=1000),
                ),
                (
                    "page_title",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("page_type", models.CharField(blank=True, default="", max_length=30)),
                (
                    "css_selector",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("text_snippet", models.TextField(blank=True, default="")),
                ("raw_text", models.TextField(blank=True, default="")),
                ("confidence_score", models.FloatField(default=0.0)),
                (
                    "extractor_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("extraction_method", models.CharField(default="rule", max_length=30)),
                ("validation_notes", models.TextField(blank=True, default="")),
                ("crawled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "raw_html_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id", "field_name"],
                        name="academic_et_entity__4b2be3_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_type", models.CharField(max_length=30)),
                ("entity_id", models.PositiveIntegerField()),
                ("target_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("skip", "Skip"),
                            ("would_create", "Would Create"),
                            ("would_update", "Would Update"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("matched_by", models.CharField(blank=True, default="", max_length=50)),
                ("diff_json", models.JSONField(blank=True, default=dict)),
                ("message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "import_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="academic_etl.importjob",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstitutionSeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("country", models.CharField(max_length=100)),
                (
                    "country_code",
                    models.CharField(blank=True, default="", max_length=2),
                ),
                ("city", models.CharField(blank=True, default="", max_length=255)),
                ("region", models.CharField(blank=True, default="", max_length=255)),
                ("website", models.URLField(blank=True, default="", max_length=500)),
                (
                    "institution_type",
                    models.CharField(
                        choices=[
                            ("university", "University"),
                            ("college", "College"),
                            ("institute", "Institute"),
                            ("institute_of_technology", "Institute Of Technology"),
                            ("polytechnic", "Polytechnic"),
                            ("graduate_school", "Graduate School"),
                            ("postgraduate_institute", "Postgraduate Institute"),
                            ("medical_university", "Medical University"),
                            ("business_school", "Business School"),
                            ("art_school", "Art School"),
                            ("high_school", "High School"),
                            ("secondary_school", "Secondary School"),
                            ("primary_school", "Primary School"),
                            ("kindergarten", "Kindergarten"),
                            ("language_center", "Language Center"),
                            ("training_center", "Training Center"),
                            ("coaching_center", "Coaching Center"),
                            ("bootcamp", "Bootcamp"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                ("source_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "source_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("confidence_score", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("discovered", "Discovered"),
                            ("valid", "Valid"),
                            ("invalid", "Invalid"),
                            ("needs_review", "Needs Review"),
                            ("crawled", "Crawled"),
                            ("crawl_failed", "Crawl Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="discovered",
                        max_length=20,
                    ),
                ),
                ("raw_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pipeline_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seeds",
                        to="academic_etl.pipelinerun",
                    ),
                ),
            ],
            options={
                "unique_together": {("pipeline_run", "name", "website")},
            },
        ),
        migrations.AddField(
            model_name="importjob",
            name="pipeline_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="import_jobs",
                to="academic_etl.pipelinerun",
            ),
        ),
        migrations.CreateModel(
            name="ExtractedUniversity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("name", models.CharField(blank=True, default="", max_length=500)),
                ("location", models.CharField(blank=True, default="", max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                ("slug", models.SlugField(blank=True, default="", max_length=500)),
                ("sponsored", models.BooleanField(blank=True, null=True)),
                ("website", models.URLField(blank=True, default="", max_length=500)),
                (
                    "global_rank",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "financials",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("student_loan_available", models.BooleanField(blank=True, null=True)),
                ("campus_student_life", models.TextField(blank=True, default="")),
                (
                    "number_of_students",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "student_to_faculty_ratio",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "international_student_ratio",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("housing_availability", models.BooleanField(blank=True, null=True)),
                (
                    "admissions_contact",
                    models.CharField(blank=True, default="", max_length=254),
                ),
                (
                    "admissions_phone",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "admissions_page_link",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("immigration_support", models.BooleanField(blank=True, null=True)),
                (
                    "university_campuses",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("country", models.CharField(blank=True, default="", max_length=100)),
                (
                    "country_code",
                    models.CharField(blank=True, default="", max_length=2),
                ),
                ("city", models.CharField(blank=True, default="", max_length=255)),
                ("region", models.CharField(blank=True, default="", max_length=255)),
                (
                    "institution_type",
                    models.CharField(
                        choices=[
                            ("university", "University"),
                            ("college", "College"),
                            ("institute", "Institute"),
                            ("institute_of_technology", "Institute Of Technology"),
                            ("polytechnic", "Polytechnic"),
                            ("graduate_school", "Graduate School"),
                            ("postgraduate_institute", "Postgraduate Institute"),
                            ("medical_university", "Medical University"),
                            ("business_school", "Business School"),
                            ("art_school", "Art School"),
                            ("high_school", "High School"),
                            ("secondary_school", "Secondary School"),
                            ("primary_school", "Primary School"),
                            ("kindergarten", "Kindergarten"),
                            ("language_center", "Language Center"),
                            ("training_center", "Training Center"),
                            ("coaching_center", "Coaching Center"),
                            ("bootcamp", "Bootcamp"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                ("raw_json", models.JSONField(blank=True, default=dict)),
                ("normalized_json", models.JSONField(blank=True, default=dict)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("completeness_score", models.FloatField(default=0.0)),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("not_validated", "Not Validated"),
                            ("valid", "Valid"),
                            ("warnings", "Warnings"),
                            ("invalid", "Invalid"),
                            ("needs_review", "Needs Review"),
                        ],
                        default="not_validated",
                        max_length=20,
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("edited", "Edited"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("review_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extracted_universities",
                        to="academic_etl.institutionseed",
                    ),
                ),
                (
                    "pipeline_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="universities",
                        to="academic_etl.pipelinerun",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "extracted universities",
            },
        ),
        migrations.CreateModel(
            name="ExtractedProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "university_slug",
                    models.SlugField(blank=True, default="", max_length=500),
                ),
                ("country", models.CharField(blank=True, default="", max_length=100)),
                (
                    "country_code",
                    models.CharField(blank=True, default="", max_length=2),
                ),
                ("campus", models.CharField(blank=True, default="", max_length=255)),
                ("program_name", models.CharField(max_length=500)),
                (
                    "degree_level",
                    models.CharField(
                        choices=[
                            ("associate", "Associate"),
                            ("diploma", "Diploma"),
                            ("bachelor", "Bachelor"),
                            ("master", "Master"),
                            ("phd", "Phd"),
                            ("postgraduate_certificate", "Postgrad Cert"),
                            ("postgraduate_diploma", "Postgrad Diploma"),
                            ("professional", "Professional"),
                            ("non_degree", "Non Degree"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                (
                    "field_of_study",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "faculty_or_school",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("duration", models.CharField(blank=True, default="", max_length=100)),
                (
                    "study_mode",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("language", models.CharField(blank=True, default="", max_length=100)),
                (
                    "tuition_fee",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("currency", models.CharField(blank=True, default="", max_length=10)),
                ("intake", models.CharField(blank=True, default="", max_length=255)),
                (
                    "application_deadline",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("admission_requirements", models.TextField(blank=True, default="")),
                ("career_outcomes", models.TextField(blank=True, default="")),
                (
                    "accreditation",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "program_url",
                    models.URLField(blank=True, default="", max_length=1000),
                ),
                (
                    "source_url",
                    models.URLField(blank=True, default="", max_length=1000),
                ),
                (
                    "is_higher_education_program",
                    models.BooleanField(blank=True, null=True),
                ),
                ("raw_json", models.JSONField(blank=True, default=dict)),
                ("normalized_json", models.JSONField(blank=True, default=dict)),
                ("confidence_score", models.FloatField(default=0.0)),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("not_validated", "Not Validated"),
                            ("valid", "Valid"),
                            ("warnings", "Warnings"),
                            ("invalid", "Invalid"),
                            ("needs_review", "Needs Review"),
                        ],
                        default="not_validated",
                        max_length=20,
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("edited", "Edited"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "extracted_university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="academic_etl.extracteduniversity",
                    ),
                ),
                (
                    "pipeline_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="academic_etl.pipelinerun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CrawledPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=1000)),
                ("final_url", models.URLField(blank=True, default="", max_length=1000)),
                ("page_type", models.CharField(default="other", max_length=30)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(blank=True, default="", max_length=500)),
                ("depth", models.PositiveSmallIntegerField(default=0)),
                ("html_hash", models.CharField(blank=True, default="", max_length=64)),
                (
                    "html_cache_path",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("fetch_error", models.TextField(blank=True, default="")),
                ("crawled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="academic_etl.institutionseed",
                    ),
                ),
                (
                    "pipeline_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="academic_etl.pipelinerun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ValidationIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_type", models.CharField(max_length=30)),
                ("entity_id", models.PositiveIntegerField()),
                (
                    "field_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("error", "Error"),
                            ("warning", "Warning"),
                            ("info", "Info"),
                        ],
                        default="warning",
                        max_length=10,
                    ),
                ),
                ("code", models.CharField(blank=True, default="", max_length=50)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pipeline_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="academic_etl.pipelinerun",
                    ),
                ),
            ],
        ),
    ]
