# Generated by Django 6.0.6 on 2026-06-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_etl", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawledpage",
            name="render_engine",
            field=models.CharField(blank=True, default="requests", max_length=20),
        ),
    ]
