# Generated by Django 6.0.6 on 2026-06-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_etl", "0002_crawledpage_render_engine"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutionseed",
            name="wikidata_qid",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="institutionseed",
            name="wikipedia_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="pipelinerun",
            name="seed_provider",
            field=models.CharField(
                default="hipolabs", help_text="hipolabs | csv | wikidata", max_length=50
            ),
        ),
    ]
