# Generated by Django 6.0.6 on 2026-06-20 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_etl", "0003_institutionseed_wikidata_qid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_name", models.CharField(max_length=100, unique=True)),
                (
                    "country_code",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2", max_length=2, unique=True
                    ),
                ),
                (
                    "currency_code",
                    models.CharField(
                        help_text="ISO 4217 (VND, INR, USD)", max_length=3
                    ),
                ),
                (
                    "numeric_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ISO 3166-1 numeric",
                        max_length=3,
                    ),
                ),
                (
                    "denomination_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Denomination abbreviations and multipliers, e.g. {"k": 1000, "tr": 1000000}',
                    ),
                ),
                (
                    "primary_languages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='ISO 639-1 codes, e.g. ["vi", "en"]',
                    ),
                ),
                (
                    "url_language_markers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='URL path markers for local language, e.g. ["/vi/", "/vn/"]',
                    ),
                ),
                (
                    "degree_level_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Local degree terms -> canonical level, e.g. {"cử nhân": "bachelor"}',
                    ),
                ),
                (
                    "crawl_frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("biweekly", "Biweekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("max_institutions", models.PositiveIntegerField(default=200)),
                (
                    "preferred_providers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Ordered list: ["wikipedia", "wikidata", "hipolabs"]',
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_crawl_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "country configs",
            },
        ),
        migrations.AddField(
            model_name="extractedprogram",
            name="tuition_amount_high",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="extractedprogram",
            name="tuition_amount_low",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="extractedprogram",
            name="tuition_fee_raw",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="extractedprogram",
            name="tuition_period",
            field=models.CharField(
                blank=True,
                default="",
                help_text="annual | semester | total | monthly",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="extractedprogram",
            name="tuition_usd_high",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="extractedprogram",
            name="tuition_usd_low",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="extracteduniversity",
            name="financials_amount_high",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="extracteduniversity",
            name="financials_amount_low",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="extracteduniversity",
            name="financials_currency",
            field=models.CharField(blank=True, default="", max_length=3),
        ),
        migrations.AddField(
            model_name="extracteduniversity",
            name="financials_raw",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="extracteduniversity",
            name="financials_usd_high",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="extracteduniversity",
            name="financials_usd_low",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="is_incremental",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="parent_run",
            field=models.ForeignKey(
                blank=True,
                help_text="Previous run this incremental run is updating",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_runs",
                to="academic_etl.pipelinerun",
            ),
        ),
        migrations.AlterField(
            model_name="pipelinerun",
            name="seed_provider",
            field=models.CharField(
                default="hipolabs",
                help_text="hipolabs | csv | wikidata | wikipedia | fanar",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="CrawlSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_code", models.CharField(max_length=2, unique=True)),
                ("country_name", models.CharField(max_length=100)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("biweekly", "Biweekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("hybrid", "Hybrid"),
                            ("crawl", "Crawl"),
                            ("gemini", "Gemini"),
                            ("fanar", "Fanar"),
                        ],
                        default="hybrid",
                        max_length=20,
                    ),
                ),
                ("discover_limit", models.PositiveIntegerField(default=200)),
                ("crawl_limit", models.PositiveIntegerField(default=50)),
                ("max_pages_per_site", models.PositiveIntegerField(default=8)),
                ("is_incremental", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="academic_etl.pipelinerun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency_code",
                    models.CharField(db_index=True, help_text="ISO 4217", max_length=3),
                ),
                (
                    "rate_to_usd",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="1 USD = X units of this currency",
                        max_digits=16,
                    ),
                ),
                ("source", models.CharField(default="frankfurter", max_length=50)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["currency_code", "-fetched_at"],
                        name="academic_et_currenc_658e8a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ExtractedSpecialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specialization_name", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "specialization_url",
                    models.URLField(blank=True, default="", max_length=1000),
                ),
                (
                    "source_url",
                    models.URLField(blank=True, default="", max_length=1000),
                ),
                ("raw_json", models.JSONField(blank=True, default=dict)),
                ("confidence_score", models.FloatField(default=0.0)),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("not_validated", "Not Validated"),
                            ("valid", "Valid"),
                            ("warnings", "Warnings"),
                            ("invalid", "Invalid"),
                            ("needs_review", "Needs Review"),
                        ],
                        default="not_validated",
                        max_length=20,
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("edited", "Edited"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "extracted_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specializations",
                        to="academic_etl.extractedprogram",
                    ),
                ),
                (
                    "pipeline_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specializations",
                        to="academic_etl.pipelinerun",
                    ),
                ),
            ],
            options={
                "unique_together": {("extracted_program", "specialization_name")},
            },
        ),
    ]
