# Generated by Django 6.0.6 on 2026-06-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academic_etl",
            "0004_countryconfig_extractedprogram_tuition_amount_high_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelinerun",
            name="seed_provider",
            field=models.CharField(
                default="wikipedia",
                help_text="wikipedia | wikidata | csv | fanar",
                max_length=50,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="institutionseed",
            unique_together={("pipeline_run", "name", "city", "website")},
        ),
    ]
